### ISSUE TITLE
Clarification about breaking the menu

### ISSUE THREAD

**Issue by MrPaulDriver** [jimkeller/menu_parent_form_ui#1]
I have been hoping that such a module would come along. Thank you

From the module description ...

> Drupal includes the dashes by default when printing this option list, but this approach is pretty brittle and will break if the text of these options changes in the future.

As for breaking the menu; what would cause this? The text of the dash pattern being changed in Drupal core, the menu hierarchy changing or wording of the menu items changing. 

Please could you clarify?

**Comment by jimkeller** [comment]
Hi Paul,

The problem would only occur if a change to Drupal core affected how it prints the menu list. It's not something that a content manager would be able to cause due to moving menus around or changing the name.

Basically, when Drupal prints the select tag for the menu, it prefixes each item with one or more dashes to indicate the level of the item. So like "-About", "--Our Mission". The module uses those dashes to determine which level something lives at (which admittedly is kind of a lame way of doing it, but it let me make this a purely front-end module). If Drupal ever changed and removed those dashes, the module would stop working. That being said, I think those dashes have been there since like Drupal 6.

Thanks for the note; I'm going to clarify that language in the readme.

**Comment by MrPaulDriver** [comment]
Thanks for the quick follow up. I think your answer makes it rather more resilient than the project page suggests.

**Comment by jimkeller** [comment]
README updated with more clarity
